import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/color';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  content: { padding: 20, paddingBottom: 20 },
  scroll: { flex: 1, marginBottom: 85 },
  headerCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
    marginBottom: 12,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  headerLeftModal: { alignItems: 'center' },
  avatarWrap: { width: 56, height: 56, borderRadius: 28, overflow: 'hidden' },
  avatar: { width: '100%', height: '100%' },
  name: { fontSize: 16, fontWeight: '600', color: '#111' },
  email: { color: '#7b6f8b', marginTop: 2 },
  editBtn: {
    backgroundColor: COLORS.primaryLightOpacity,
    paddingVertical: 1,
    paddingHorizontal: 8,
    borderRadius: 100,
    marginRight: '2%',
  },
  editText: { color: COLORS.primaryLightOpacityFill, fontWeight: '600' },
  sectionTitle: { color: COLORS.temp, fontSize: 16, marginTop: '3%', marginBottom: 8, fontWeight: '500' },
  whiteCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 15,
    paddingTop: 10,
    paddingBottom: 10,
    marginBottom: 12,
    elevation: 2,
  },
  redCard: {
    backgroundColor: COLORS.red,
    borderRadius: 12,
    padding: 15,
    marginTop: '5%',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 10,
    justifyContent: 'space-between',
  },
  rowLeft: { flexDirection: 'row', alignItems: 'center' },
  iconPlaceholder: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#efe6ff',
    marginRight: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowLabel: { fontSize: 15, color: COLORS.temp, fontWeight: '500' },
  chev: { color: '#bdb3c8', fontSize: 15 },
  iconPlaceholderWhite: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fff',
    marginRight: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowLabelWhite: { fontSize: 15, color: '#fff', fontWeight: '500' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
  overlayFill: { flex: 1 },
  bottomSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 30,
    elevation: 6,
  },
  statusBarOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  sheetTitle: { fontSize: 22, fontWeight: '700', color: '#111', marginTop: '2%', marginBottom: 8 },
  langRight: { marginTop: Platform.OS === 'web' ? '-5.5%' : '-10.5%' },
  langText: { marginRight: 8, color: '#333', fontWeight: '600' },
  langHint: { color: '#6b6b6b', fontSize: 12, marginTop: 10 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeBtn: { padding: 8, borderRadius: 8 },
  closeX: { fontSize: 20, color: '#111', fontWeight: '700' },
});

export default styles;
