import { StyleSheet } from 'react-native'
import { COLORS } from '../../constants/color'

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.white },
    content: { padding: 20, paddingBottom: 20 },
    scroll: { flex: 1, marginBottom: 85 },
    backIcon: {
        width: 40,
        height: 40,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: COLORS.borderWhite,
        marginBottom: 6,
    },
    headerCard: {
        backgroundColor: COLORS.white,
        borderRadius: 12,
        padding: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 3,
        marginBottom: 12,
    },
    headerLeft: { flexDirection: 'row', alignItems: 'center' },
    avatarWrap: { width: 56, height: 56, borderRadius: 28, overflow: 'hidden' },
    avatar: { width: '100%', height: '100%' },
    name: { fontSize: 16, fontWeight: '600', color: '#111' },
    email: { color: '#7b6f8b', marginTop: 2 },
    sectionTitle: { color: COLORS.temp, fontSize: 16, marginTop: '3%', marginBottom: 8, fontWeight: '500' },
    whiteCard: {
        backgroundColor: COLORS.white,
        borderRadius: 12,
        padding: 15,
        paddingTop: 10,
        paddingBottom: 10,
        marginBottom: 12,
        elevation: 2,
    },
    redCard: {
        backgroundColor: COLORS.red,
        borderRadius: 12,
        paddingVertical: 20,
        paddingHorizontal: 18,
        marginTop: '5%',
    },
    iconPlaceholderWhite: {
        width: 38,
        height: 38,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#fff',
        marginRight: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 10,
        justifyContent: 'space-between',
    },
    rowLeft: { flexDirection: 'row', alignItems: 'center' },
    rowLabel: { fontSize: 15, color: COLORS.temp, fontWeight: '500' },
    chev: { color: '#6b6b6b', fontSize: 15 },
})

export default styles
