import { COLORS } from '@/constants/color';
import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  scrollView: {
    padding: 16,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1E293B',
    marginVertical: 24,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    margin: 16,
    shadowColor: '#475569',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 16,
    marginTop: 16,
  },
  subtitle2: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 16,
    color: '#93C5FD',
  },
  errorText: {
    fontSize: 14,
    color: '#DC2626',
    marginTop: 12,
  },
  retryText: {
    fontSize: 14,
    color: '#2563EB',
    marginTop: 10,
    textDecorationLine: 'underline',
  },
  streamingContainer: {
    backgroundColor: '#F1F5F9',
    borderRadius: 14,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  streamingLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 6,
  },
  streamingText: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 20,
  },
  sourcesButtonContainer: {
    alignItems: 'center',
    marginTop: 16,
  },
  sourcesButton: {
    backgroundColor: '#2563EB',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 999,
  },
  sourcesButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  sheetOverlayTouchable: {
    flex: 1,
  },
  sheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
    maxHeight: '80%',
  },
  sheetHeader: {
    marginBottom: 5,
  },
  sheetTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sheetTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingLeft: 5,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
  },
  sheetCount: {
    fontSize: 16,
    fontWeight: '700',
    color: '#6fa1df',
    backgroundColor: '#ddecff',
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: '2%',
    borderRadius: 100,
  },
  iconClose: {
    width: 40,
    height: 40,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.borderWhite,
  },
  sheetContent: {
    flex: 1,
    minHeight: 0,
  },
  webViewContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  webViewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: '#E5E7EB',
  },
  webViewClose: {
    padding: 8,
  },
  webview: {
    flex: 1,
  },
  webViewModalContainer: {
    paddingTop: 8,
    maxHeight: '92%',
    height: '92%',
    paddingBottom: 0,
  },
  webViewBody: {
    flex: 1,
    marginTop: 8,
  },
  webViewInner: {
    flex: 1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  sheetCloseButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  sheetCloseText: {
    fontSize: 14,
    color: '#2563EB',
    fontWeight: '700',
  },
  // Categories styles
  categoriesContainer: {
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#E2E8F0',
    marginTop: '-6%',
    maxHeight: 56,
    marginLeft: -16,
    marginRight: -16,
  },
  categoriesContent: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    gap: 8,
    justifyContent: 'center',
  },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 24,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    gap: 8,
  },
  categoryChipActive: {
    backgroundColor: '#1E293B',
    borderColor: '#1E293B',
  },
  chipIconContainer: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
    lineHeight: 14,
  },
  categoryChipTextActive: {
    color: '#FFFFFF',
  },
  // Modal styles for questions
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  questionsModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    flex: 0.45,
    flexDirection: 'column',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  headerWithBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  categorySquareIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#E8F0FE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 25,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#f0f0f0eb',
  },
  questionsListContainer: {
    flex: 1,
    marginBottom: 12,
  },
  questionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 0,
    marginVertical: 2.5,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
  },
  questionText: {
    flex: 1,
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '500',
    marginRight: 12,
    lineHeight: 20,
  },
  // Disclaimer styles
  disclaimerContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'flex-end',
  },
  disclaimerText: {
    fontSize: 10,
    fontWeight: '400',
    color: '#94A3B8',
    lineHeight: 14,
    textAlign: 'right',
    maxWidth: '90%',
  },
});
